### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by psyclone241** [afropolymath/papers-v2#1]
Hi, I liked your article on the original "papers" app, but the repository seems incomplete. Do you have either the original or this version in a release branch somewhere? Just wondering. No worries if you don't.

**Comment by afropolymath** [comment]
@psyclone241 Sorry I'm just seeing this. Here you go - https://github.com/afropolymath/papers

**Comment by psyclone241** [comment]
@afropolymath No worries! I had that repo already cloned. It's been awhile since I posted this comment. I'll see if this answers my original question, lol.

Thank You and God bless!
